name: Verifies PR are ready for merge

on:
  pull_request:
    branches:
      - main

jobs:
  verify-docfx-build:
    runs-on: ubuntu-latest
    name: Test docfx build
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Install docfx
        run: dotnet tool install --global docfx --version 2.77.0

      - name: Build Documentation
        run: make build
