name: Verifies PR are ready for merge

on:
  pull_request:
    branches:
      - main

jobs:
  verify-docfx-build:
    runs-on: ubuntu-latest
    name: Test docfx build
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: list files
        run: ls -la -R ./doc

      - name: list files in submodules
        run:  ls -la -R ./submodules/*/doc

      - name: Install docfx
        run: dotnet tool install --global docfx --version 2.71.0

      - name: Build Documentation
        run: make build
